name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports: 
          - 5433:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: generic-e-comerce-pg
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Create fake jwtConstants
        run: |
          mkdir -p src/infra/auth
          echo "export const jwtConstants = { secret: 'test-secret-constant' };" > src/infra/auth/constants.ts
        env: 
          DATABASE_URL: "postgresql://docker:docker@localhost:5433/apisolid?schema=public"

      - run: npm run test
